<img src="images/logodwengo.png" alt="Banner" width="150"/>

<div>
    <font color=#690027 markdown="1">
        <h1>FUNCTIONALITEITEN  BIJ NUMPY-LIJSTEN</h1> 
    </font>
</div>

<div class="alert alert-block alert-success"> 
In deze notebook krijg je voorbeelden voorgeschoteld van functionaliteiten bij NumPy-lijsten. 
</div>

### Module importeren

In [1]:
import numpy as np

<div>
    <font color=#690027 markdown="1">
        <h2>1. Data</h2> 
    </font>
</div>

Je zal met de vier NumPy-lijsten werken uit de volgende code-cel. Voer na de code-cel voor de import ook deze code-cel uit.  

In [2]:
x = np.array([28,  40,  41,  44,  45,  51,  54,  57,  57,  60,  62,  72,  74, 90, 113])
y = np.array([33,  35,  47,  35,  55,  56,  50,  50,  70,  65,  35,  82,  80, 95, 100])
rij = np.array([2, 7, 10, 5])
rij2 = np.array([2, 4, 6, 8, 10, 12, 14, 16, 18, 20])

Je kan het type opvragen:

In [3]:
type(x)

numpy.ndarray

`x` heeft het type *ndarray*.

<div>
    <font color=#690027 markdown="1">
        <h2>2. Index</h2> 
    </font>
</div>

Soms is het interessant om te weten waar een bepaalde waarde in een NumPy-lijst voorkomt, of wat het gemiddelde is van een lijst getallen. 

<div>
    <font color=#690027 markdown="1">
        <h3>Voorbeeld 2.1: index</h3> 
    </font>
</div>

Elk element in een NumPy-lijst heeft een **index**. Je ziet die vooraan in de tabel hierboven staan.
M.b.v. de index kan je een bepaald element van een NumPy-lijst opvragen. Zo is het eerste element in de NumPy-lijst `x` het element met index 0. Hoe je die waarde opvraagt, wordt getoond in de volgende code-cel: 

In [4]:
# element opvragen
x[0]                                            # element uit lijst x met index 0

28

In [5]:
# element opvragen
x[6]                                            # zevende element uit lijst x

54

In [6]:
# element opvragen
x[-1]

113

### Opdracht 2.1
- Vraag het negende element op van NumPy-lijst `y`.
- Vraag het voorlaatste element op van de NumPy-lijst `y`.

In [7]:
# voorbeeldoplossing
y[8]

70

In [8]:
# voorbeeldoplossing
y[-2]

95

<div>
    <font color=#690027 markdown="1">
        <h3>Voorbeeld 2.2: een element opzoeken</h3> 
    </font>
</div>

Met de functie `where()` van de module NumPy kan je achterhalen wat de index is van een bepaald element. 

In [9]:
# index van bepaald element
np.where(x == 60)

(array([9], dtype=int64),)

In [10]:
# index van bepaald element
np.where(x == 57)

(array([7, 8], dtype=int64),)

<div class="alert alert-box alert-info">
<span style="background-color:whitesmoke; font-family:consolas; font-size:1em;">==</span> is een vergelijkingsoperator.
</div>

### Opdracht 2.2
- Het hoeveelste element van de NumPy-lijst `y` is 56?
- Welk element van de NumPy-lijst `x` heeft dezelfde index als 56 uit NumPy-lijst `y`?

In [11]:
# voorbeeldoplossing
np.where(y == 56)

(array([5], dtype=int64),)

In [12]:
# voorbeeldoplossing
x[5]

51

Antwoord:

Antwoord: 56 is het zesde element van de NumPy-lijst `y`. Het element 51 van NumPy-lijst `x` heeft dezelfde index.

<div>
    <font color=#690027 markdown="1">
        <h3>Voorbeeld 2.3: een element verwijderen</h3> 
    </font>
</div>

Je kunt via de *index* elementen uit de NumPy-lijst 'rij' verwijderen met de functie `delete()`.

In [13]:
print(rij)

[ 2  7 10  5]


In [14]:
kortererij = np.delete(rij, 1)   # maak nieuwe lijst die dezelfde is als eerste lijst maar zonder element met index 1
print(kortererij)

[ 2 10  5]


In [15]:
kortsterij = np.delete(rij, [1, 3]) # maak nieuwe lijst die dezelfde is als eerste lijst maar zonder elementen met index 1 en 3
print(kortsterij)

[ 2 10]


### Opdracht 2.3
Beschouw de NumPy-lijst waarnaar wordt verwezen met de variabele `rij2`. Maak hiervan een kortere NumPy-lijst door de elementen 8, 12 en 18 te verwijderen m.b.v. `delete()`. 

In [16]:
# voorbeeldoplossing
kortererij2 = np.delete(rij2, [3, 5, 8])
print(kortererij2)

[ 2  4  6 10 14 16 20]


<div>
    <font color=#690027 markdown="1">
        <h3>Voorbeeld 2.4: dezelfde elementen ineens verwijderen</h3> 
    </font>
</div>

Je kan alle elementen '35' uit `y` verwijderen. Voer daarvoor de volgende code-cel uit.

In [17]:
index = np.where(y == 35)                 
uitgedunde_y = np.delete(y, index)    
print(y) 
print(uitgedunde_y)

[ 33  35  47  35  55  56  50  50  70  65  35  82  80  95 100]
[ 33  47  55  56  50  50  70  65  82  80  95 100]


### Opdracht 2.4
Verwijder alle elementen '57' uit `x`.

In [18]:
# voorbeeldoplossing
plaats = np.where(x == 57)                 
uitgedunde_x = np.delete(x, plaats)    
print(x) 
print(uitgedunde_x)

[ 28  40  41  44  45  51  54  57  57  60  62  72  74  90 113]
[ 28  40  41  44  45  51  54  60  62  72  74  90 113]


<div>
    <font color=#690027 markdown="1">
        <h3>Voorbeeld 2.5: een deel van een NumPy-lijst selecteren</h3> 
    </font>
</div>

A.d.h.v. de *index* kan je een deel van een NumPy-lijst selecteren. Python gebruikt daar een *halfopen interval* voor.

In [19]:
stukvanrij2 = rij2[3: 7]      # halfopen interval [3, 7[
print(stukvanrij2)

[ 8 10 12 14]


In [20]:
eerstehelftrij2 = rij2[:5]     
tweedehelftrij2 = rij2[5:]
print(eerstehelftrij2)
print(tweedehelftrij2)

[ 2  4  6  8 10]
[12 14 16 18 20]


### Opdracht 2.5
- Beschouw de NumPy-lijst waarnaar wordt verwezen met de variabele `y`. Maak een nieuwe NumPy-lijst die bestaat uit de elementen met index 1 t.e.m. index 8. Verwijs naar de nieuwe NumPy-lijst met `y_nieuw`. 
- Maak een nieuwe NumPy-lijst `nieuwelijst` die de drie laatste elementen van `rij` bevat.
- Maak een nieuwe NumPy-lijst `nieuwstelijst` die eerste drie elementen van `x` bevat.

In [21]:
# voorbeeldoplossing
y_nieuw = y[1:9]
nieuwelijst = rij[1:]
nieuwstelijst = x[:3]
print(y_nieuw)
print(nieuwelijst)
print(nieuwstelijst)

[35 47 35 55 56 50 50 70]
[ 7 10  5]
[28 40 41]


<div>
    <font color=#690027 markdown="1">
        <h2>3. Handig voor statistiek</h2> 
    </font>
</div>

<div>
    <font color=#690027 markdown="1">
        <h3>Voorbeeld 3.1: kleinste en grootste waarde in een NumPy-lijst</h3> 
    </font>
</div>

Om de grootste of kleinste waarde op te vragen in een Numpy-lijst, kan je gebruikmaken van de ingebouwde Python-methodes `min()` en `max()`.<br>
Maar je kan ook de functies `min()` en `max()` van NumPy aanwenden, zoals in de volgende code-cellen.

In [22]:
x.min()

28

In [23]:
np.min(x)

28

In [24]:
np.max(y)

100

### Opdracht 3.1
- Vraag de grootste waarde op van de NumPy-lijst `rij`.

In [25]:
# voorbeeldoplossing
np.max(rij)

10

<div>
    <font color=#690027 markdown="1">
        <h3> Voorbeeld 3.2: gemiddelde en som van de elementen van een NumPy-lijst</h3> 
    </font>
</div>

Met de functie `sum()` uit de module NumPy kan je de som van de elementen van een NumPy-lijst berekenen en met de functie `mean()` het gemiddelde. 

In [26]:
# som berekenen
x_som = np.sum(x)
print(x_som)

888


In [27]:
# gemiddelde berekenen
x_gemiddelde = np.mean(x)                         # gemiddelde van alle elementen van lijst x
y_gemiddelde_middelstevijf = np.mean(y[5:10])     # gemiddelde van y[5] t.e.m. y[9]
print(x_gemiddelde, y_gemiddelde_middelstevijf)   # laat beide resultaten zien, gescheiden door komma 

59.2 58.2


### Opdracht 3.2
- Bereken het gemiddelde van de elementen van de NumPy-lijst `y`.
- Bereken het gemiddelde van de eerste 10 elementen van de NumPy-lijst `x`. 
- Bereken de som van de elementen van de NumPy-lijst `y`.

In [28]:
# voorbeeldoplossing
y_gemiddelde = np.mean(y) 
x_gemiddelde_eerstetien = np.mean(x[0:10]) 
y_som = np.sum(y)

print(y_gemiddelde, y_som, x_gemiddelde_eerstetien)

59.2 888 47.7


Antwoord:

Antwoord:
-  het gemiddelde van de elementen van de NumPy-lijst `y` is 60,4;
-  het gemiddelde van de eerste 10 elementen van de NumPy-lijst `x` is 906
-  de som van de elementen van de NumPy-lijst `y` is 47,7.

<div>
    <font color=#690027 markdown="1">
        <h3>Voorbeeld 3.3: variantie en standaardafwijking</h3> 
    </font>
</div>

Met de functies `var()` en `std()` vraag je de variantie en de standaardafwijking op van alle elementen uit een NumPy-lijst.

In [29]:
x_variantie = np.var(x)
x_standaardafwijking = np.std(x)
print(x_variantie, x_standaardafwijking)

429.62666666666667 20.727437532571813


### Opdracht 3.3
- Bereken de variantie van de elementen van de NumPy-lijst `y`.
- Bereken de standaardafwijking van de elementen van de NumPy-lijst `y`. 

In [30]:
# voorbeeldoplossing
y_variantie = np.var(y)
y_standaardafwijking = np.std(y)

<div>
    <font color=#690027 markdown="1">
        <h3>Voorbeeld 3.4:  de lengte van een NumPy-lijst</h3> 
    </font>
</div>

Je kunt met de functie `len()` het aantal elementen van een NumPy-lijst opvragen.

In [31]:
len(rij)

4

### Opdracht 3.4
Vraag de lengte op van de NumPy-lijst `x`. 

In [32]:
# voorbeeldoplossing
len(x)

15

<div>
    <font color=#690027 markdown="1">
        <h3>Voorbeeld 3.5: NumPy-lijsten samenvoegen</h3> 
    </font>
</div>

Je kunt NumPy-lijsten samenvoegen met de functie `append()`.

In [33]:
samengevoegdelijst = np.append(rij, rij2)
print(samengevoegdelijst)

[ 2  7 10  5  2  4  6  8 10 12 14 16 18 20]


### Opdracht 3.5
Voeg de NumPy-lijst `x` samen met de NumPy-lijst `rij`. `x` komt eerst in de samengestelde NumPy-lijst.

In [34]:
# voorbeeldoplossing
samengevoegdelijst2 = np.append(x, rij)
print(samengevoegdelijst2)

[ 28  40  41  44  45  51  54  57  57  60  62  72  74  90 113   2   7  10
   5]


<div>
    <font color=#690027 markdown="1">
        <h2>4. Automatisch genereren van een NumPy-lijst</h2> 
    </font>
</div>

<div>
    <font color=#690027 markdown="1">
        <h3>Voorbeeld 4.1: een NumPy-lijst  van nullen</h3> 
    </font>
</div>

Je kan een NumPy-lijst met een bepaalde lengte laten genereren en opvullen met nullen.

In [35]:
nullijst = np.zeros(5)
print(nullijst)

[0. 0. 0. 0. 0.]


Je kan de elementen overschrijven door een andere waarde.

In [36]:
nullijst[3] = 2
print(nullijst)

[0. 0. 0. 2. 0.]


### Opdracht 4.1
- Maak een NumPy-lijst met 101 nullen erin en refereer eraan met de variabele `allemaal nullen`. 
- Laat de NumPy-lijst zien.
- Vraag de lengte van `allemaal nullen` op.

In [37]:
# voorbeeldoplossing
allemaalnullen = np.zeros(101)
print(allemaalnullen)
print(len(allemaalnullen))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0.]
101


<div>
    <font color=#690027 markdown="1">
        <h3>Voorbeeld 4.2: arange() en linspace()</h3> 
    </font>
</div>

Met NumPy kan je ook automatisch lijsten genereren door een van de NumPy-functies `linspace()` of `arange()` te gebruiken. 

In [38]:
lijst1 = np.linspace(0, 10, 11)
print(lijst1)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [39]:
lijst2 = np.arange(10)
print(lijst2)

[0 1 2 3 4 5 6 7 8 9]


In [40]:
lijst3 = np.arange(-10, 15, step=5)
print(lijst3)

[-10  -5   0   5  10]


### Opdracht 4.2
- Probeer in de voorgaande voorbeelden bepaalde patronen te herkennen. Experimenteer daarvoor met de parameters.

- Genereer vervolgens de volgende NumPy-lijsten:
<p> &nbsp; &nbsp; [2 &nbsp; 4 &nbsp; 6 &nbsp; 8]</p>
<p> &nbsp; &nbsp; [-3. &nbsp; 0. &nbsp; 3. &nbsp; 6. &nbsp; 9. &nbsp; 12. &nbsp; 15. &nbsp; 18. &nbsp; 21.]</p>

In [41]:
# voorbeeldoplossing

- Voer de volgende code-cel uit. 

In [42]:
lijst4 = np.arange(3,500,step=4)
lijst5 = np.linspace(3, 500, 200)

- Laat `lijst4` en `lijst5` zien. 
- Bepaal de lengte van beide lijsten.

In [43]:
# voorbeeldoplossing
print(lijst4)
print(lijst5)

[  3   7  11  15  19  23  27  31  35  39  43  47  51  55  59  63  67  71
  75  79  83  87  91  95  99 103 107 111 115 119 123 127 131 135 139 143
 147 151 155 159 163 167 171 175 179 183 187 191 195 199 203 207 211 215
 219 223 227 231 235 239 243 247 251 255 259 263 267 271 275 279 283 287
 291 295 299 303 307 311 315 319 323 327 331 335 339 343 347 351 355 359
 363 367 371 375 379 383 387 391 395 399 403 407 411 415 419 423 427 431
 435 439 443 447 451 455 459 463 467 471 475 479 483 487 491 495 499]
[  3.           5.49748744   7.99497487  10.49246231  12.98994975
  15.48743719  17.98492462  20.48241206  22.9798995   25.47738693
  27.97487437  30.47236181  32.96984925  35.46733668  37.96482412
  40.46231156  42.95979899  45.45728643  47.95477387  50.45226131
  52.94974874  55.44723618  57.94472362  60.44221106  62.93969849
  65.43718593  67.93467337  70.4321608   72.92964824  75.42713568
  77.92462312  80.42211055  82.91959799  85.41708543  87.91457286
  90.4120603   92.90954774  95

- Bepaal met Python het element in `lijst5` dat dezelfde index heeft als het element '251' in `lijst4`.

In [44]:
# voorbeeldoplossing
np.where(lijst4 == 251)

(array([62], dtype=int64),)

In [45]:
# voorbeeldoplossing
lijst5[62]

157.84422110552765

- '255' is een element van `lijst4`. Maak een nieuwe NumPy-lijst door enkel de elementen uit `lijst4` te behouden vanaf '255'. <br> Verwijs naar deze nieuwe NumPy-lijst met de variabele `lijst4_staart` en laat de nieuwe NumPy-lijst zien. 

In [46]:
# voorbeeldoplossing
np.where(lijst4 == 255)

(array([63], dtype=int64),)

In [47]:
# voorbeeldoplossing
lijst4_staart = lijst4[63:]
print(lijst4_staart)

[255 259 263 267 271 275 279 283 287 291 295 299 303 307 311 315 319 323
 327 331 335 339 343 347 351 355 359 363 367 371 375 379 383 387 391 395
 399 403 407 411 415 419 423 427 431 435 439 443 447 451 455 459 463 467
 471 475 479 483 487 491 495 499]


<div>
    <font color=#690027 markdown="1">
        <h2>5. Datatype van de elementen van een NumPy-lijst</h2> 
    </font>
</div>

<div>
    <font color=#690027 markdown="1">
        <h3>Voorbeeld 5.1: bit en byte</h3> 
    </font>
</div>

<div class="alert alert-block alert-info"> 
Een <b>bit</b> is een informatie-eenheid. De term is afkomstig van <b>binary digit</b>. Het is een eenheid die enkel de waarden 0 en 1 kan aannemen. <br>Acht bits vormen samen een <b>byte</b>. Er zijn 256 mogelijke bytes.
</div>

Natuurlijke getallen zijn gehele getallen die positief zijn. Het is dus niet nodig om het toestandsteken expliciet te vermelden (de + hoef je niet te noteren). <br>
De natuurlijke getallen van 0 t.e.m. 255 kan je voorstellen met een byte. 77 bv. komt overeen met 01001101.

### Opdracht 5.1
Leg uit waarom er 256 mogelijke combinaties zijn om een byte te vormen.

In [48]:
# voorbeeldoplossing
2**8

256

Antwoord:

Antwoord: Voor elke plaats in de byte zijn er twee mogelijkheden en er zijn acht plaatsen. Dus er zijn $2^8=256$ mogelijkheden.

<div>
    <font color=#690027 markdown="1">
        <h3>Voorbeeld 5.2: type van de elementen</h3> 
    </font>
</div>

<div class="alert alert-box alert-info">
    De elementen van een NumPy-lijst zijn getallen: <em>integers</em>, <em>floating-point numbers</em>, en ook nog <em>complex numbers</em>. <br>De gehele getallen hebben (in principe) het type <b>int</b> en de niet-gehele getallen hebben het type <b>float</b>.
    
Je kan het type van de elementen opvragen met <span style="background-color:whitesmoke; font-family:consolas; font-size:1em;">dtype</span>. <br>
    Het type wordt dan teruggegeven samen met een getal dat overeenkomt met het aantal bits nodig is om een getal op te slaan in het geheugen.<br><br>
    Bv. het type <b>int64</b> voor gehele getallen: het bereik van <span style="background-color:whitesmoke; font-family:consolas; font-size:1em;">int64</span> is van -9223372036854775808 tot 9223372036854775807.  <br>
</div>

In [49]:
lijst5.dtype

dtype('float64')

In [50]:
lijst2.dtype

dtype('int32')

### Opdracht 5.2

- Vraag het type op van de elementen van `x`.

In [51]:
# voorbeeldoplossing
x.dtype

dtype('int32')

- Zijn de elementen van `lijst1` gehele getallen of niet? 
- Vraag het type op van de elementen van `lijst1`.
- Komt dit overeen met wat je verwachtte?

In [52]:
# voorbeeldoplossing
lijst1.dtype

dtype('float64')

<div class="alert alert-block alert-warning"> 
Deze functionaliteiten komen meer of minder aan bod, afhankelijk van de notebooks die je doorloopt. Weet dat je hier de nodige zaken kunt komen opzoeken. <br><br>
    Toepassingen op wat je leerde in deze notebook vind je bv. in de STEM-notebooks Klimaat ('CO$_{2}$', 'De Keelingcurve' en de notebooks over de smeltende gletsjers). 
</div>

<img src="images/cclic.png" alt="Banner" align="left" width="100"/><br><br>
Notebook Python in wiskunde, zie Computationeel denken - Programmeren in Python van <a href="http://www.aiopschool.be">AI Op School</a>, van F. wyffels & N. Gesquière in licentie gegeven volgens een <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Naamsvermelding-NietCommercieel-GelijkDelen 4.0 Internationaal-licentie</a>. 