# Wiskundig modelleren met een Lesliematrix 

In [1]:
# nodige modules importeren
import numpy as np
import matplotlib.pyplot as plt

In [2]:
# nijlpaarden worden maximaal 45 jaar
leeftijden = np.arange(3)
print(leeftijden)

[0 1 2]


In [3]:
# bevolkingsmatrix met aantallen per leeftijd
n0 = np.zeros(3)  # bevolkingsmatrix met drie leeftijdscategorieen
n0[0] = 204        # aantal nuljarige dieren
n0[1] = 60         # aantal eenjarige dieren
n0[2] = 36         # aantal tweejarige dieren
print(n0)
print(n0.shape)

[204.  60.  36.]
(3,)


In [4]:
# vruchtbaarheid
# worden vruchtbaar vanaf leeftijd van 1 jaar
# wordt eerste rij in vierkante matrix - Lesliematrix 
vruchtbaarheid = np.array([[0.0, 2.5, 1.5]])

# overlevingscijfers
# van de 0-jarigen wordt 60 % 1 jaar, van de 1-jarigen wordt 40 % 2 jaar
overleving = np.array([0.6, 0.4, 0.0])  # -> nog naar diagonaalmatrix

print(vruchtbaarheid)
print(overleving)

print(vruchtbaarheid.shape)
print(overleving.shape)

[[0.  2.5 1.5]]
[0.6 0.4 0. ]
(1, 3)
(3,)


In [5]:
# Lesliematrix L
L_onderstedeel = np.identity(3) * overleving
print(L_onderstedeel)
print(L_onderstedeel.shape)

[[0.6 0.  0. ]
 [0.  0.4 0. ]
 [0.  0.  0. ]]
(3, 3)


In [6]:
L = np.concatenate((vruchtbaarheid,L_onderstedeel))
print(L)
print(L.shape)

[[0.  2.5 1.5]
 [0.6 0.  0. ]
 [0.  0.4 0. ]
 [0.  0.  0. ]]
(4, 3)


In [7]:
# laatste rij wegdoen
L = L[0:3,]
print(L)
print(L.shape)

[[0.  2.5 1.5]
 [0.6 0.  0. ]
 [0.  0.4 0. ]]
(3, 3)


De Lesliematrices hebben als dimensie 3 x 3. Ze kunnen vermenigvuldigd worden met een kolommatrix van dimensie 3 x 1, wat dus de dimensie van de bevolkingsmatrix moet zijn. Dit klopt voor n0.

In [8]:
n0 = np.transpose(n0)

In [9]:
# na 1 jaar
# matrixvermenigvuldiging met functie dot() die de betreffende matrices als parameters meekrijgt; dot(A, B) 
n1 = np.dot(L, n0)
print(n1)

[204.  122.4  24. ]


In [10]:
# na 2 jaar
n2 = np.dot(L, n1)
print(n2)

[342.   122.4   48.96]


In [11]:
# na 5 jaar
n3 = np.dot(L, n2)
n4 = np.dot(L, n3)
n5 = np.dot(L, n4)
print(n5)

[692.28   351.864   91.0656]


In [18]:
# na 5 jaar, kortere manier
A = L
for i in range(4): 
    A = L * A
    print(i+1, A)

#n5 = np.dot(A, n0)
#print(n5)


1 [[0.   6.25 2.25]
 [0.36 0.   0.  ]
 [0.   0.16 0.  ]]
2 [[ 0.    15.625  3.375]
 [ 0.216  0.     0.   ]
 [ 0.     0.064  0.   ]]
3 [[0.00000e+00 3.90625e+01 5.06250e+00]
 [1.29600e-01 0.00000e+00 0.00000e+00]
 [0.00000e+00 2.56000e-02 0.00000e+00]]
4 [[0.000000e+00 9.765625e+01 7.593750e+00]
 [7.776000e-02 0.000000e+00 0.000000e+00]
 [0.000000e+00 1.024000e-02 0.000000e+00]]


In [19]:
# na 5 jaar
n5 = np.dot(A, n0)
print(n5)

[6.132750e+03 1.586304e+01 6.144000e-01]
